### ISSUE TITLE
lsp branch can not auto complete header file

### ISSUE THREAD

**Issue by wutianjun5858** [jinzhongjia/neovim-config#1]
![1681909959491_88C56ED4-B1BC-4e11-905C-CC398B951D06](https://user-images.githubusercontent.com/25163353/233085507-04683bf4-77c3-44b4-8025-09334c5616a2.png)

**Comment by jinzhongjia** [comment]
You need to check if mason has installed `clangd` correctly, use `:Mason`

**Comment by jinzhongjia** [comment]
you may see like this:
![image](https://user-images.githubusercontent.com/41784264/233115485-16e643e3-4d07-49ce-8448-33287e41d179.png)

**Comment by wutianjun5858** [comment]
> you should see like this: ![image](https://user-images.githubusercontent.com/41784264/233115485-16e643e3-4d07-49ce-8448-33287e41d179.png)

I have installed clangd, but it's not work. maybe you can test it.

**Comment by jinzhongjia** [comment]
![image](https://user-images.githubusercontent.com/41784264/233247030-a8c4c8ce-4cb9-410c-8819-fc9ffac028d4.png)

in my computre, it works well

**Comment by jinzhongjia** [comment]
Does only header file completion fail?

**Comment by jinzhongjia** [comment]
you can see lsp status through `:LspInfo`

like this:
![image](https://user-images.githubusercontent.com/41784264/233247201-128b793e-40d3-43c1-8178-a03fe01b82e8.png)

**Comment by wutianjun5858** [comment]
![image](https://user-images.githubusercontent.com/25163353/233250206-4877fcab-e1da-446f-b28a-c5a3fc13d555.png)

this is LspInfo:
![image](https://user-images.githubusercontent.com/25163353/233250310-db26fda4-5a9c-402b-a442-c48f60ae9dad.png)

It's just not auto complete header file

**Comment by jinzhongjia** [comment]
clangd is not correctly mounted to the current buffer
If lspconfig is automatically configured, it should automatically mount the operation
