### ISSUE TITLE
You are trying to call the setup function of indent-blankline version 2, but you have version 3 installed.

### ISSUE THREAD

**Issue by yxsongbo** [jinzhongjia/neovim-config#2]
我刚刚接触neovim，用了您的配置文件，可以指教一下这里要如何修改吗

**Comment by yxsongbo** [comment]
[coc.nvim] Error on install coc-css: Error: Request timeout after 10000ms
安装的时候还出现了这个问题

**Comment by jinzhongjia** [comment]
你需要自行开启全局的代理，coc的所有包均是拉取npm

**Comment by jinzhongjia** [comment]
coc的配置由段时间没用了，我去更新一下
近两个月我都在主用内置的lsp，也就是`hybrid`分支

**Comment by jinzhongjia** [comment]
关于coc分支插件更新已经完成，现在使用不会出现报错提示了
> [coc.nvim] Error on install coc-css: Error: Request timeout after 10000ms
这个问题时coc从npm拉取包失败，使用全局代理即可

另外提一句，我其实不推荐你们使用我的配置，我的配置更应该是作为一种参考，而不是直接拿来用

**Comment by yxsongbo** [comment]
处理 User 自动命令 "VeryLazy" 时发生错误:
You are trying to call the setup function of indent-blankline version 2, but you have version 3 ins
talled.
Take a look at the GitHub wiki for instructions on how to migrate, or revert back to version 2.
请按 ENTER 或其它命令继续
这个错误怎么解决呢？

**Comment by yxsongbo** [comment]
> 处理 User 自动命令 "VeryLazy" 时发生错误: You are trying to call the setup function of indent-blankline version 2, but you have version 3 ins talled. Take a look at the GitHub wiki for instructions on how to migrate, or revert back to version 2. 请按 ENTER 或其它命令继续 这个错误怎么解决呢？



> 关于coc分支插件更新已经完成，现在使用不会出现报错提示了
> 
> > [coc.nvim] Error on install coc-css: Error: Request timeout after 10000ms
> > 这个问题时coc从npm拉取包失败，使用全局代理即可
> 
> 另外提一句，我其实不推荐你们使用我的配置，我的配置更应该是作为一种参考，而不是直接拿来用

我才刚刚学习，自己配置还无从下手

**Comment by yxsongbo** [comment]
你更新之后，我要怎么同步您的配置呢？

**Comment by jinzhongjia** [comment]
> 处理 User 自动命令 "VeryLazy" 时发生错误: You are trying to call the setup function of indent-blankline version 2, but you have version 3 ins talled. Take a look at the GitHub wiki for instructions on how to migrate, or revert back to version 2. 请按 ENTER 或其它命令继续 这个错误怎么解决呢？

你把你本地的配置删除，重新拉取我的配置即可
这个问题是因为这个插件更新了新版本，导致出现的问题（旧版本的插件配置方式发生了改变）

**Comment by jinzhongjia** [comment]
> 你更新之后，我要怎么同步您的配置呢？

你可以选择fork我的这个仓库，然后我的仓库会作为你仓库的上游存在，然后你可选地同步上游我的配置即可
此时你就有你自己独立的仓库了，然后关于配置管理的话，请使用git 进行 管理
单纯的文件下载后防止并不稳妥

**Comment by jinzhongjia** [comment]
关于刚开始学习配置，需要慢慢来，可以先用着我的配置试试，或者可以尝试`spacevim` `nvcard` `doomvim`这些预配置的vim发行版（均支持neovim）
然后边使用边研究配置文件，最终你就可以自己定制neovim了
初期肯定会出现看不明白的情况，参照我在b站的视频提到的文档查询函数使用即可

**Comment by yxsongbo** [comment]
> You are trying to call the setup function of indent-blankline version 2, but you have version 3 ins
> talled.

非常感谢您的指教

**Comment by jinzhongjia** [comment]
如果没有其他问题，我就暂时将此issue关闭了，有问题你可以重新打开它

**Comment by yxsongbo** [comment]
> 如果没有其他问题，我就暂时将此issue关闭了，有问题你可以重新打开它

好的，谢谢啦
